version: "3"
networks:
  application:
    driver: bridge

services:
  app:
    build:
      context: .              # karena Dockerfile ada di root
      dockerfile: Dockerfile
    container_name: service_c_project_sora
    ports:
      - "8000:80"             # host:container
    volumes:
      - .:/var/www/html       # agar bisa dev-mode/live reload
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=service_c_db
      - DB_PORT=5432
      - DB_DATABASE=stock-db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      - application

  db:
    image: postgres:15
    container_name: service_c_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stock-db
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
